### ISSUE TITLE
Big viewer bug when zooming

### ISSUE THREAD

**Issue by TimWolz** [qkitgroup/qkit#78]
The x-Axis does not scale correctly in a line plot when zooming in or out. See attached screenshots. Basically the resonance frequency dip is at two different frequencies. Depending on the zoom level it can be tens of MHz apart. 
Especially if you don't know this bug and want to have a quick look for frequency changes it can be really confusing.
Issue might be python3 related.
![zomm_in](https://user-images.githubusercontent.com/34345962/78340452-6d72b680-7596-11ea-8768-0f32fcce7754.PNG)
![zoom_out](https://user-images.githubusercontent.com/34345962/78340454-6e0b4d00-7596-11ea-8665-a34a9069deea.PNG)

**Comment by rotzinger** [comment]
Could not be verified.

**Comment by Schneider1** [comment]
It's a tricky one: It only appears when you have two screens with different scaling setting in Windows. This is mostly relevant when you work on a laptop with external screen connected.

It is pretty obvious that different elements in the graph get scaled differently, i.e. the axis and the displayed data do not have the same size and therefore do not match.

The bug is already known in pyqtgraph https://github.com/pyqtgraph/pyqtgraph/issues/756
